collections:
  SpriteServer:
    output: true
  SpriteDatabase:
    output: true
  DocumentRepository:
    output: true
  GraphRepository:
    output: true
  SpriteTransaction:
    output: true
  tutorials:
    output: true
  types:
    output: true