baseurl: "/sprite"
collections:
  SpriteServer:
    output: true
  SpriteDatabase:
    output: true
  DocumentModality:
    output: true
  GraphModality:
    output: true
  SpriteTransaction:
    output: true
  tutorials:
    output: true
  types:
    output: true